
management:
  endpoints:
    web:
      exposure:
        include: info, routes, filters, refresh

server:
  port: 8087



gateway:
  zuul:
    filters:
      base-path: src/main/resources/groovy

spring:
  profiles: local

